# BLOCK_FOCUS_GLOBAL_BEGIN
windowrule = no_initial_focus on, match:class .*
windowrule = suppress_event activatefocus, match:class .*
# BLOCK_FOCUS_GLOBAL_END
windowrule = no_initial_focus on, match:class ^(steam)$
windowrule = suppress_event activatefocus, match:class ^(steam)$
windowrule = suppress_event activatefocus, match:class ^(discord)$

# Omarchy screensaver rules
windowrule = fullscreen on, match:class ^(org\.omarchy\.screensaver)$
windowrule = no_initial_focus on, match:class ^(org\.omarchy\.screensaver)$
